package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/chieworks/mstore/internal/source"
	"github.com/chieworks/mstore/internal/store"
)

const hfMirrorEndpoint = "https://hf-mirror.com"

type downloadScriptOptions struct {
	UseUV    bool
	HFMirror bool
}

type downloadScriptModel struct {
	Name     string `json:"name"`
	Version  string `json:"version"`
	Current  bool   `json:"current"`
	Provider string `json:"provider"`
	Repo     string `json:"repo"`
	Revision string `json:"revision"`
	Command  string `json:"command"`
}

type downloadScriptPlan struct {
	Models []downloadScriptModel `json:"models"`
	Script string                `json:"script"`
}

type downloadScriptCommand struct {
	Command   string
	SyncAfter bool
}

func (a *app) downloadScript(args []string) error {
	f := newFlags("generate")
	all := f.Bool("all", false, "")
	currentOnly := f.Bool("current-only", false, "")
	useUV := f.Bool("uv", false, "")
	hfMirror := f.Bool("hf-mirror", false, "")
	if err := f.Parse(args); err != nil {
		return usageError("%v", err)
	}
	refs := f.Args()
	if *all && len(refs) > 0 {
		return usageError("generate accepts model refs or --all, not both")
	}
	if !*all && len(refs) == 0 {
		return usageError("generate requires model refs or --all")
	}
	if *currentOnly && !*all {
		return usageError("--current-only requires --all")
	}

	versions, err := a.downloadScriptVersions(refs, *all, *currentOnly)
	if err != nil {
		return err
	}
	plan, err := makeDownloadScript(versions, downloadScriptOptions{UseUV: *useUV, HFMirror: *hfMirror})
	if err != nil {
		return err
	}
	if a.global.json {
		return writeJSON(a.out, plan)
	}
	_, err = fmt.Fprint(a.out, plan.Script)
	return err
}

func (a *app) downloadScriptVersions(refs []string, all, currentOnly bool) ([]store.Version, error) {
	if !all {
		selected := make(map[string]store.Version, len(refs))
		for _, ref := range refs {
			v, err := a.store.Resolve(ref)
			if err != nil {
				return nil, err
			}
			selected[v.Name+"@"+v.Version] = v
		}
		return sortedVersions(selected), nil
	}

	versions, err := a.store.List("")
	if err != nil {
		return nil, err
	}
	selected := make(map[string]store.Version, len(versions))
	for _, v := range versions {
		if currentOnly && !v.Current {
			continue
		}
		selected[v.Name+"@"+v.Version] = v
	}
	return sortedVersions(selected), nil
}

func sortedVersions(selected map[string]store.Version) []store.Version {
	versions := make([]store.Version, 0, len(selected))
	for _, v := range selected {
		versions = append(versions, v)
	}
	sort.Slice(versions, func(i, j int) bool {
		if versions[i].Name == versions[j].Name {
			return versions[i].Version < versions[j].Version
		}
		return versions[i].Name < versions[j].Name
	})
	return versions
}

func makeDownloadScript(versions []store.Version, opts downloadScriptOptions) (downloadScriptPlan, error) {
	plan := downloadScriptPlan{}
	seen := make(map[string]bool, len(versions))
	modelScopeRevisions := make(map[string]map[string]bool)
	for _, v := range versions {
		src := v.Manifest.Source
		if src.Provider != "ms" {
			continue
		}
		if modelScopeRevisions[src.Repo] == nil {
			modelScopeRevisions[src.Repo] = make(map[string]bool)
		}
		modelScopeRevisions[src.Repo][src.Revision] = true
	}
	var commands []downloadScriptCommand
	var warnings []string
	seenWarnings := make(map[string]bool)
	for _, v := range versions {
		src := v.Manifest.Source
		if _, err := source.ParseRef(src.Provider + ":" + src.Repo + "@" + src.Revision); err != nil {
			return plan, fmt.Errorf("%s@%s: invalid source in manifest: %w", v.Name, v.Version, err)
		}
		command, err := downloadCommand(src.Provider, src.Repo, src.Revision, opts)
		if err != nil {
			return plan, fmt.Errorf("%s@%s: %w", v.Name, v.Version, err)
		}
		plan.Models = append(plan.Models, downloadScriptModel{
			Name: v.Name, Version: v.Version, Current: v.Current,
			Provider: src.Provider, Repo: src.Repo, Revision: src.Revision, Command: command,
		})
		key := src.Provider + "\x00" + src.Repo + "\x00" + src.Revision
		if seen[key] {
			continue
		}
		seen[key] = true
		commands = append(commands, downloadScriptCommand{
			Command: command,
			SyncAfter: src.Provider == "ms" &&
				len(modelScopeRevisions[src.Repo]) > 1,
		})
		if src.Provider == "ms" && !isImmutableModelScopeRevision(src.Revision) {
			warning := "ModelScope revision " + src.Repo + "@" + src.Revision + " is not an immutable commit ID; it may move before the script runs."
			if !seenWarnings[warning] {
				seenWarnings[warning] = true
				warnings = append(warnings, warning)
			}
		}
	}
	sort.Strings(warnings)

	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Generated by mstore generate. Recorded source revisions are used.\n")
	for _, warning := range warnings {
		b.WriteString("# WARNING: ")
		b.WriteString(warning)
		b.WriteString("\n")
	}
	if opts.UseUV {
		b.WriteString("# This script uses uvx; install uv before running it.\n")
	}
	if opts.HFMirror {
		b.WriteString("# Hugging Face downloads use https://hf-mirror.com.\n")
	}
	b.WriteString("# Authenticate with Hugging Face or ModelScope first when a model is private or gated.\n")
	b.WriteString("set -euo pipefail\n")
	for _, command := range commands {
		b.WriteString("\n")
		b.WriteString(command.Command)
		if command.SyncAfter {
			b.WriteString("\n# Preserve this ModelScope revision before downloading the next one.\n")
			b.WriteString("mstore sync --provider ms")
		}
		b.WriteString("\n")
	}
	plan.Script = b.String()
	return plan, nil
}

func isImmutableModelScopeRevision(revision string) bool {
	if len(revision) != 40 && len(revision) != 64 {
		return false
	}
	for _, r := range revision {
		if (r < '0' || r > '9') && (r < 'a' || r > 'f') && (r < 'A' || r > 'F') {
			return false
		}
	}
	return true
}

func downloadCommand(provider, repo, revision string, opts downloadScriptOptions) (string, error) {
	var command string
	switch provider {
	case "hf":
		command = "hf download " + shellQuote(repo) + " --revision " + shellQuote(revision)
		if opts.UseUV {
			command = "uvx --from huggingface_hub " + command
		}
		if opts.HFMirror {
			command = "HF_ENDPOINT=" + shellQuote(hfMirrorEndpoint) + " " + command
		}
	case "ms":
		command = "modelscope download --model " + shellQuote(repo) + " --revision " + shellQuote(revision)
		if opts.UseUV {
			command = "uvx " + command
		}
	default:
		return "", fmt.Errorf("unsupported provider %q", provider)
	}
	return command, nil
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}
