package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/chieworks/mstore/internal/source"
	"github.com/chieworks/mstore/internal/store"
)

type downloadScriptModel struct {
	Name     string `json:"name"`
	Version  string `json:"version"`
	Current  bool   `json:"current"`
	Provider string `json:"provider"`
	Repo     string `json:"repo"`
	Revision string `json:"revision"`
	Command  string `json:"command"`
}

type downloadScriptPlan struct {
	Models []downloadScriptModel `json:"models"`
	Script string                `json:"script"`
}

func (a *app) downloadScript(args []string) error {
	f := newFlags("generate")
	all := f.Bool("all", false, "")
	currentOnly := f.Bool("current-only", false, "")
	if err := f.Parse(args); err != nil {
		return usageError("%v", err)
	}
	refs := f.Args()
	if *all && len(refs) > 0 {
		return usageError("generate accepts model refs or --all, not both")
	}
	if !*all && len(refs) == 0 {
		return usageError("generate requires model refs or --all")
	}
	if *currentOnly && !*all {
		return usageError("--current-only requires --all")
	}

	versions, err := a.downloadScriptVersions(refs, *all, *currentOnly)
	if err != nil {
		return err
	}
	plan, err := makeDownloadScript(versions)
	if err != nil {
		return err
	}
	if a.global.json {
		return writeJSON(a.out, plan)
	}
	_, err = fmt.Fprint(a.out, plan.Script)
	return err
}

func (a *app) downloadScriptVersions(refs []string, all, currentOnly bool) ([]store.Version, error) {
	if !all {
		selected := make(map[string]store.Version, len(refs))
		for _, ref := range refs {
			v, err := a.store.Resolve(ref)
			if err != nil {
				return nil, err
			}
			selected[v.Name+"@"+v.Version] = v
		}
		return sortedVersions(selected), nil
	}

	versions, err := a.store.List("")
	if err != nil {
		return nil, err
	}
	selected := make(map[string]store.Version, len(versions))
	for _, v := range versions {
		if currentOnly && !v.Current {
			continue
		}
		selected[v.Name+"@"+v.Version] = v
	}
	return sortedVersions(selected), nil
}

func sortedVersions(selected map[string]store.Version) []store.Version {
	versions := make([]store.Version, 0, len(selected))
	for _, v := range selected {
		versions = append(versions, v)
	}
	sort.Slice(versions, func(i, j int) bool {
		if versions[i].Name == versions[j].Name {
			return versions[i].Version < versions[j].Version
		}
		return versions[i].Name < versions[j].Name
	})
	return versions
}

func makeDownloadScript(versions []store.Version) (downloadScriptPlan, error) {
	plan := downloadScriptPlan{}
	seen := make(map[string]bool, len(versions))
	for _, v := range versions {
		src := v.Manifest.Source
		if _, err := source.ParseRef(src.Provider + ":" + src.Repo + "@" + src.Revision); err != nil {
			return plan, fmt.Errorf("%s@%s: invalid source in manifest: %w", v.Name, v.Version, err)
		}
		command, err := downloadCommand(src.Provider, src.Repo, src.Revision)
		if err != nil {
			return plan, fmt.Errorf("%s@%s: %w", v.Name, v.Version, err)
		}
		key := src.Provider + "\x00" + src.Repo + "\x00" + src.Revision
		if seen[key] {
			continue
		}
		seen[key] = true
		plan.Models = append(plan.Models, downloadScriptModel{
			Name: v.Name, Version: v.Version, Current: v.Current,
			Provider: src.Provider, Repo: src.Repo, Revision: src.Revision, Command: command,
		})
	}

	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Generated by mstore generate. Recorded source revisions are used.\n")
	b.WriteString("# Authenticate with hf or modelscope first when a model is private or gated.\n")
	b.WriteString("set -euo pipefail\n")
	for _, m := range plan.Models {
		b.WriteString("\n")
		b.WriteString(m.Command)
		b.WriteString("\n")
	}
	plan.Script = b.String()
	return plan, nil
}

func downloadCommand(provider, repo, revision string) (string, error) {
	switch provider {
	case "hf":
		return "hf download " + shellQuote(repo) + " --revision " + shellQuote(revision), nil
	case "ms":
		return "modelscope download --model " + shellQuote(repo) + " --revision " + shellQuote(revision), nil
	default:
		return "", fmt.Errorf("unsupported provider %q", provider)
	}
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}
